name: "vercel deployment"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: install dependency
        run: npm ci

      - name: lint code
        run: npm run lint

      - name: run test cases
        run: CI=true npm test -- --watch=false

      - name: make react build
        run: npm run build

      - name: install vercel cli
        run: npm install --global vercel

      - name: deployment on vercel
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: vercel --prod --yes --token="${{ secrets.VERCAL_TOKEN }}"