name: "eslint test work flow"

on:
  push:
  pull_request:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: install dependency
        run: npm ci

      - name: lint code
        run: npm run lint

      - name: run test cases
        run: CI=true npm test -- --watch=false

      - name: make react build
        run: npm run build

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
          retention-days: 7

